spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/socialNetwork
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: qwerty
    hikari:
      minimum-idle: 10
      maximum-pool-size: 70
      idle-timeout: 600000
      connection-test-query: SELECT 1
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        ddl-auto: create-drop
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    generate-ddl: true